CREATE TABLE members (
    id INT PRIMARY KEY AUTO_INCREMENT,
    member_no VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


